### ISSUE TITLE
sr config reload bug

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#1]
when makinn a config change using the /sr config
it will wipe the whole file and create a new one without any # comments

**Comment by DoNotSpamPls** [comment]
It shouldn't cause any issues with the plugin.

**Comment by DoNotSpamPls** [comment]
wow i closed the wrong issue

**Comment by DoNotSpamPls** [comment]
This can't be fixed by any means, since the YAML standard doesn't support comments all that well.
There are only two options:
1. completely remove comments from the config (except at the very top)
2. remove the /sr config feature (more realistic)
