### ISSUE TITLE
tasklist for skinclear

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#13]
- make it permission op &/or skinsrestorer.playercmds.clear
- [prevent internal error when doing 2x clear]
- [make the line only appear when you have the right permissions so when player does not have  
skinsrestorer.playercmds.clear or op, it won't see the command in /skin (same as /sr in /skin when)]

optional:
1. make 2 extra lines in inlocale for these things: https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/c541be72a7886dfddf601f96da27c0e667b80e04/src/skinsrestorer/bungee/commands/PlayerCommands.java#L51 (dont forget both bukkit & bungee)
1.2 make it update the new lines from the above auto update when missing (old locale)

**Comment by DoNotSpamPls** [comment]
For first and third one, I don't really want to overcomplicate things, and /skin clear will just be available with skinsrestorfer.playercmds

**Comment by xknat** [comment]
k approved. troller might be able to do that

**Comment by DoNotSpamPls** [comment]
Fixed second one in issue #22

**Comment by DoNotSpamPls** [comment]
Closing this issue, request 1.2 is already in its own issue
