### ISSUE TITLE
option for toggleing between /skin set or /skin

### ISSUE THREAD

**Issue by LazosPlaying** [DoNotSpamPls/SkinsRestorerX#17]
## MY SUGGESTION !

add config option to toggle between `/skin set` and `/skin` command

Regards,
~Lazos

**Comment by LazosPlaying** [comment]
Gave myself +1 because i like my idea.
(feelzLikeAjerk 😂 plox... plox... y I evn du diz)

Bye Bye 👋 



😂

**Comment by DoNotSpamPls** [comment]
Added in commit 59924ca
