### ISSUE TITLE
Default Skins option is broken on BungeeCord

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#19]
### What doesn't work (or what feature do you request)?
default skins does not work well for bungee

### How to reproduce the bug? (if a bug)
i used 13.1.3 on spigot with defaultskins it did work
but some how on bungee it does not seem to work

### What version of SkinsRestorer do you use?
13.1.3

**Comment by DoNotSpamPls** [comment]
The bug is caused by the plugin not creating .player files for the players

**Comment by xknat** [comment]
code is missing. https://github.com/DoNotSpamPls/SkinsRestorerX/blob/677199c13a490525ce9c8698c30d9e7bb3670538/src/main/java/skinsrestorer/bukkit/SkinsRestorer.java#L229-L231 is in bukkit but missing for bungee
