### ISSUE TITLE
TLauncher interferes with SkinsRestorer

### ISSUE THREAD

**Issue by Logics4** [DoNotSpamPls/SkinsRestorerX#21]
### What doesn't work (or what feature do you request)?

SkinsRestorer's skins don't show if player is using TLauncher.

### How to reproduce the bug? (if a bug)

1 - Join with TLauncher (and ely.by skins turned on) in a server with SkinsRestorer.
2 - Here you go.
This doesn't happen if ely.by skins are turned off on TLauncher's settings.

### What version of SkinsRestorer do you use?

It should affect all the versions including the latest.

**Comment by DoNotSpamPls** [comment]
I have contacted TLauncher's team, waiting for a reply.

**Comment by xknat** [comment]
I got a reply from TLauncher team
Hello. We will note this in our list of tasks, but so far we have quite a lot of cases and it is not known when we proceed to correct this.

You can describe in more detail how your plugin works, and where the skins themselves are from.
from @DoNotSpamPls in discord\#coolpeeps

**Comment by DoNotSpamPls** [comment]
This is like, super low-priority and also can't be fixed on our side. Closing issue.
