### ISSUE TITLE
Don't send locale messages if the string is empty

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#27]
someone requested me to remove the sr line.
told him this is not possible unless you self code

can you make a if sr_line = " " inside the  locale it will skip this line on display

[request = [click here](https://www.spigotmc.org/threads/skinsrestorer.37225/page-154#post-2784088)  ]

**Comment by DoNotSpamPls** [comment]
This may or may not help -https://github.com/DoNotSpamPls/SkinsRestorerX/commit/948e8010e29481819636db9590dd1468038dc3e2

**Comment by DoNotSpamPls** [comment]
55b8185 helps, but it's not a full-proof solution
