### ISSUE TITLE
1.7 support in the plugin is half-working

### ISSUE THREAD

**Issue by DoNotSpamPls** [DoNotSpamPls/SkinsRestorerX#32]
On the protocol hack, 1.8 players can see skins, while 1.7 players can't. I suspect this is because of the format changes that 1.8 introduced.

**Comment by Logics4** [comment]
"Can't work on this in the current repo for now, so fork the original one and use that" Now we can.
https://github.com/DoNotSpamPls/SkinsRestorerX/commit/46b66dafdb9641745e565d3b5dc7311707ee981b
