### ISSUE TITLE
Add %skin as a variable

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#34]
### What doesn't work (or what feature do you request)?
request: add a %skin to [ADMIN_SET_SKIN  = "&2You set %player's skin.";]

**Comment by Logics4** [comment]
Maybe something like "You set (player name)'s skin to (skin name)." ...?

**Comment by xknat** [comment]
^ thats what id did mean :D

**Comment by xknat** [comment]
something with 
sender.sendMessage(Locale.SKIN_CHANGE_SUCCESS.replace("%player", sb.toString())); 
in https://github.com/DoNotSpamPls/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/commands/SrCommand.java#L85
would be a step ahead
