### ISSUE TITLE
multiworld compatibility

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#45]
### What doesn't work (or what feature do you request)?
we only added mvcore world dependency but we should try and support more world plugin since mvcore is not the only one used. 

### How to reproduce the bug? (if a bug)
just use multiworld here: https://dev.bukkit.org/projects/multiworld-v-2-0
### What version of SkinsRestorer do you use?
13.2

this is it prob:
https://dev.bukkit.org/projects/multiworld-v-2-0/pages/api

**Comment by xknat** [comment]
should be fixed in #46

**Comment by DoNotSpamPls** [comment]
Should have been fixed in 5d2323e
