### ISSUE TITLE
Unknown host exception (getmeproxy.com) should warn to check firewall

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#50]
We need to add more exception info and not java errors that they will report all the time:

https://pastebin.com/hsf6UXQQ

**Comment by DoNotSpamPls** [comment]
We already catch IOException, and UnknownHostException is a sub-exception of IOException

**Comment by xknat** [comment]
@DoNotSpamPls i know. but we want skinsrestorer to be ease in use and we don't want them to keep sending us report messages but read error's and try to solve it themselves.

**Comment by Logics4** [comment]
`try {
     // code
} catch(UnknownHostException e) {
throw new RuntimeException("Insert informative message here saying to users to check their firewall.");

// optional
e.printStacktrace();
}`

Maybe this. Do we use a try-catch block or we use `throws`?

**Comment by xknat** [comment]
@Logics4 can you put that in here:
https://github.com/DoNotSpamPls/SkinsRestorerX/blob/3ac969517187624074527efabcfadbde6c0ff90c/src/main/java/skinsrestorer/shared/utils/ProxyManager.java#L31-L40

**Comment by DoNotSpamPls** [comment]
This was added in d2a9a1c
