### ISSUE TITLE
Some proxies are blocked from Mojang API

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#53]
it does respond. but not what we want...
code 403 forbidden because some proxy's did block mojang api.
skinsrestorer must search for next one...

issue by: iKoner#0003
https://thumb.gyazo.com/thumb/1200/_122948c2ff462cc18a4ab18535615ce2-png.jpg

**Comment by xknat** [comment]
we gonna do in #60

**Comment by DoNotSpamPls** [comment]
I checked up with some sources, and there is no evidence that Mojang blocks any users on their side. This means that the issue is on the user's side, probably some kind of a firewall.
