### ISSUE TITLE
skins without perms for bungee

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#6]
a lot i mean a lot of request are that they want to have to do commands without a permissions system or to even do permissions because some fail.

possible to make the skinswithout work in bungee? 💯

**Comment by Logics4** [comment]
Tbh, is it so hard to open BungeeCord config.yml and add "skinsrestorer.playercmds" to the default group?
But whatever, I guess...

**Comment by DoNotSpamPls** [comment]
Fixed in 48b7509
