### ISSUE TITLE
catch ConnectException for checkVersion

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#61]
we should put this: 
https://github.com/DoNotSpamPls/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/SkinsRestorer.java#L48

above this error:
https://www.spigotmc.org/threads/skinsrestorer.37225/page-156#post-2836586
to make it more clear that is just failed to check a version and did not make a crash (some don't read java because of language barrier

we might need to catch ConnectException
https://github.com/DoNotSpamPls/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/SkinsRestorer.java#L46-L47

might be something we want to do with #60

**Comment by DoNotSpamPls** [comment]
Can't do that, since we just shade the Spiget API.
