### ISSUE TITLE
"Please wait a minute before requesting that skin again. (Rate Limited)"

### ISSUE THREAD

**Issue by jariahtiainen** [DoNotSpamPls/SkinsRestorerX#65]
### What doesn't work (or what feature do you request)?
"/skin" command gives "Please wait a minute before requesting that skin again. (Rate Limited)"
and in server console I get "Switching to proxy to get skin property." and "Proxy list is empty. Getting one." After that nothing happens.
### How to reproduce the bug? (if a bug)
By giving that /skin command
### What version of SkinsRestorer do you use?
13.2

**Comment by xknat** [comment]
@jariahtiainen download 13.3 on our discord server in announcements!

**Comment by jariahtiainen** [comment]
Alright, that did the trick! Me and my little minecrafters say: THANK YOU! =)
