### ISSUE TITLE
BungeeCord crash

### ISSUE THREAD

**Issue by SeDark** [DoNotSpamPls/SkinsRestorerX#69]
### What doesn't work (or what feature do you request)?

https://pastebin.com/5apw93TZ

For some reason the bungeecord log has been filled with this error, until java has been unable to do more and has shown "OutOfMemoryError GC overhead limit exceeded".

I have been using SkinRestorer for a long time and I never had problems.
I have not modified my iptables or firewall at this time

### How to reproduce the bug? (if a bug)

I do not know how to reproduce it or when it happens.

### What version of SkinsRestorer do you use?

13.3

**Comment by xknat** [comment]
@sedark.

There is a reason for the error.

Make sure your firewall is not blocking getmeproxy.com

**Comment by SeDark** [comment]
No, I've talked to you in discord, that or any other isn't blocked.

**Comment by xknat** [comment]
Making a issue here will not get you far. Reach out to me on discord is the only hole you got right now.

**Comment by xknat** [comment]
Hope*

**Comment by SeDark** [comment]
I opened this before contacting you in discord

**Comment by xknat** [comment]
Then message me again. You won't by any addition on this github right now with this issue

**Comment by xknat** [comment]
We already know this issue. And i have already posted it

**Comment by zBoringDrop** [comment]
Same error, please it seems to be a critical error. Can you work in priority in this please?

**Comment by SeDark** [comment]
https://github.com/SeDark/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/shared/utils/ProxyManager.java

If you want a solution until the authors correct the error, compile the source with the class that I mentioned.

It is not a great solution but it is a patch for now.

**Comment by zBoringDrop** [comment]
Ehm...

I don' t know, i'm not good for this..
