### ISSUE TITLE
/skinsmenu in bungee

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#7]
/skinsmenu in bungee would be awesome

**Comment by DoNotSpamPls** [comment]
If I recall correctly, BungeeCord doesn't have any APIs for showing GUIs to the end user, so unfortunately this isn't possible. Users would have to use the Spigot version to get the menu

**Comment by Logics4** [comment]
Maybe using plugin messaging channels? SkinsRestorer already uses them for communication between Bungee and the Spigot module at the moment.
