### ISSUE TITLE
Add the possibility to use own proxies

### ISSUE THREAD

**Issue by Alexre** [DoNotSpamPls/SkinsRestorerX#70]
Hi!

### What doesn't work (or what feature do you request)?
Since the mojang api change, we were forced to update to the latest skinsrestorer. We were using the latest version of sr with a custom proxy list.

Why? Big servers can have more than 600 - almost 1000 per bungeecord, the main ip of the vps gets blocked by mojang's limit rate and the proxy too (one proxy for too many users is not sufficient) 

Can you add the possibility to use a custom proxy list to fix this?

Thank you :)

**Comment by xknat** [comment]
@Alexre we are working for big host. Contact me over skinsrestorer discord server or by pm please.

**Comment by DoNotSpamPls** [comment]
Hi there!

We're definetely working on this (#26) and I promise it will be added in the next release of SkinsRestorer.
