### ISSUE TITLE
op issue with authme reloaded

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#8]
this issue did appear after version 13.1.3 with the fix of:
"/skin notch disable usage of commandblocks till /restart or /deop -> /op"

Th3Tr0LLeR/SkinsRestorer---Maro#209

**Comment by DoNotSpamPls** [comment]
Referencing https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/209
